version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    rebase-strategy: auto
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"