run:
  timeout: 5m
  tests: true
  build-tags:
    - testing

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
