builds:
  - main: main.go
    binary: qovery
    ldflags:
      - -s -w -X github.com/qovery/qovery-cli/pkg.Version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: qovery-cli
    goarm: 6
    tap:
      owner: qovery
      name: homebrew-qovery-cli
    url_template: "https://github.com/Qovery/qovery-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: qovery
      email: contact@qovery.com
    folder: Formula
    homepage: "https://docs.qovery.com"
    description: "Deploy modern application in seconds"
    skip_upload: false
    install: |
      bin.install "qovery"
scoop:
  url_template: "https://github.com/Qovery/qovery-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: qovery
    name: scoop-qovery-cli
  commit_author:
    name: qovery
    email: contact@qovery.com
  homepage: "https://docs.qovery.com"
  description: "Deploy modern application in seconds"
  license: GPL3
  persist:
  - "data"
  - "config.toml"
